# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsrole < Formula
  desc ""
  homepage "https://github.com/toolschest/awsrole"
  version "1.0"

  on_macos do
    url "https://github.com/toolschest/awsrole/releases/download/v1.0/awsrole_1.0_darwin_all.tar.gz"
    sha256 "bf68818e2fab79253fcecc97b03cb3f73aa8377fea72eaba0bbdaedddb8f839a"

    def install
      bin.install "awsrole"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toolschest/awsrole/releases/download/v1.0/awsrole_1.0_linux_arm64.tar.gz"
      sha256 "c62164019c49d23968b713886ed352f4d4202ade388f91ee6f2cb0090fe0074c"

      def install
        bin.install "awsrole"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toolschest/awsrole/releases/download/v1.0/awsrole_1.0_linux_amd64.tar.gz"
      sha256 "c322cf410a45404fb011e7bfa2ff204b937f3a9f3cb26814080e57d3bfa644f8"

      def install
        bin.install "awsrole"
      end
    end
  end
end
