# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsrole < Formula
  desc ""
  homepage "https://github.com/toolschest/awsrole"
  version "1.0"

  on_macos do
    url "https://github.com/toolschest/awsrole/releases/download/v1.0/awsrole_1.0_darwin_all.tar.gz"
    sha256 "d0e0f8ad3bfcca9113ca1b101246e4da3e35338afb664437243105cd780080b0"

    def install
      bin.install "awsrole"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toolschest/awsrole/releases/download/v1.0/awsrole_1.0_linux_arm64.tar.gz"
      sha256 "6cb756988c99901a64a6d576bd624e4b3331ee8caab2e36d1c0643264cd0447e"

      def install
        bin.install "awsrole"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toolschest/awsrole/releases/download/v1.0/awsrole_1.0_linux_amd64.tar.gz"
      sha256 "3fa6148df6d7cc24497b5ab6140184196812a4af07bda8f72ff56e1697a74a14"

      def install
        bin.install "awsrole"
      end
    end
  end
end
